//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع ضبط.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف ضبط.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی پیش‌فرض.
        /// </summary>
        public static string Default_Category {
            get {
                return ResourceManager.GetString("Default_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ دستگاه ورودی صوتی یافت نشد..
        /// </summary>
        public static string Error_NoInputDevices {
            get {
                return ResourceManager.GetString("Error_NoInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ضبط صوت: {0}.
        /// </summary>
        public static string Error_Recording_Format {
            get {
                return ResourceManager.GetString("Error_Recording_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره برچسب‌ها با خطا مواجه شد: {0}.
        /// </summary>
        public static string Error_SaveTags_Format {
            get {
                return ResourceManager.GetString("Error_SaveTags_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در شروع ضبط: {0}.
        /// </summary>
        public static string Error_StartRecording_Format {
            get {
                return ResourceManager.GetString("Error_StartRecording_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در توقف ضبط: {0}.
        /// </summary>
        public static string Error_StopRecording_Format {
            get {
                return ResourceManager.GetString("Error_StopRecording_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی:.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل:.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خواننده:.
        /// </summary>
        public static string Label_Singer {
            get {
                return ResourceManager.GetString("Label_Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع ضبط:.
        /// </summary>
        public static string Label_Source {
            get {
                return ResourceManager.GetString("Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00:00.
        /// </summary>
        public static string RecordingTime_Initial {
            get {
                return ResourceManager.GetString("RecordingTime_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ناشناس.
        /// </summary>
        public static string Unknown_File {
            get {
                return ResourceManager.GetString("Unknown_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواننده ناشناس.
        /// </summary>
        public static string Unknown_Singer {
            get {
                return ResourceManager.GetString("Unknown_Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر نام فایل پس از ضبط ناموفق بود: {0}.
        /// </summary>
        public static string Warning_RenameAfterRecord_Format {
            get {
                return ResourceManager.GetString("Warning_RenameAfterRecord_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضبط صدا.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
